version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: intelli-chat-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: intelli-chat
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
